spring.config.import=optional:file:.env[.properties]

# Spring Configs
spring.application.name=tca
server.port=7057

# JPA Configs
spring.datasource.url=${PG_CONNECTIONSTRING_MODEL}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

# CustomKeys
tca.email.send=${SEND_EMAIL}

# JWT Key
tca.security.token-secret=${JWT_SECRET_KEY}

# Maileroo Configuration
tca.email.smtp-host=${SMTP_HOST}
tca.email.smtp-password=${SMTP_PASSWORD}
tca.email.smtp-sending-key=${SMTP_SENDING_KEY}
tca.email.smtp-base-url=https://smtp.maileroo.com/api/v2