spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework.web.client.RestClient=DEBUG

# Spring Configs
spring.application.name=tca
server.port=7057

# JPA Configs
spring.datasource.url=${PG_CONNECTIONSTRING_MODEL}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

# JWT Key
tca.security.token-secret=${JWT_SECRET_KEY}

# CustomKeys
tca.email.send=${SEND_EMAIL}

# Maileroo Configuration
tca.email.smtp-host=${SMTP_HOST}
tca.email.smtp-password=${SMTP_PASSWORD}
tca.email.smtp-sending-key=${SMTP_SENDING_KEY}
tca.email.smtp-base-url=https://smtp.maileroo.com/api/v2


# Python Microservice
tca.ai.host.url=${PY_HOST_URL}
tca.ai.host.secret-key=${PY_SECRET_KEY}